-- ==============================================================================
-- 🛡️ FITPRO SUITE PRO — INTEGRIDAD REFERENCIAL, CONCURRENCIA & REALTIME RLS
-- ==============================================================================
-- Este script configura:
-- 1. Tablas relacionales con Foreign Keys y Constraints (ON DELETE CASCADE)
-- 2. Control de Concurrencia Optimista (columna 'version' y 'updated_at')
-- 3. Publicación Realtime de Supabase para sincronización multi-dispositivo sin sobreescrituras
-- 4. Políticas de Row Level Security (RLS) aisladas por Gym (tenant), Coach y Atleta
--
-- ⚠️ REQUISITO: El user_metadata de cada usuario debe contener 'gym_id' y 'role'.
--    Al registrar: options.data = { full_name, role, gym_id }
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABLAS Y CLAVES PRIMARIAS / SECUNDARIAS CON INTEGRIDAD REFERENCIAL
-- ------------------------------------------------------------------------------

-- TABLA: CLIENTS (Expedientes de Atletas)
CREATE TABLE IF NOT EXISTS clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  auth_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  coach_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  nombre text NOT NULL,
  email text,
  telefono text,
  edad integer DEFAULT 28,
  genero text DEFAULT 'Masculino',
  objetivo text DEFAULT 'Hipertrofia',
  nivel text DEFAULT 'Intermedio',
  peso numeric(5,2) DEFAULT 75.0,
  altura numeric(5,2) DEFAULT 175.0,
  porcentaje_grasa numeric(4,1) DEFAULT 15.0,
  porcentaje_musculo numeric(4,1) DEFAULT 40.0,
  estado_membresia text DEFAULT 'activa',
  adherencia text DEFAULT '100%',
  must_change_password boolean DEFAULT false,
  password_provisional text,
  version integer DEFAULT 1,
  datos_completos jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- TABLA: PLANES (Rutinas Biomecánicas)
CREATE TABLE IF NOT EXISTS planes (
  id text PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  cliente text NOT NULL,
  objetivo text,
  nivel text,
  frecuencia integer DEFAULT 4,
  division text,
  rpe_objetivo numeric(3,1) DEFAULT 8.0,
  rir_objetivo numeric(3,1) DEFAULT 2.0,
  volumen_semanal jsonb,
  dias jsonb,
  suplementacion jsonb,
  observaciones text,
  version integer DEFAULT 1,
  fecha timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- TABLA: DIETAS (Planes Nutricionales & Macros)
CREATE TABLE IF NOT EXISTS dietas (
  id text PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  cliente text NOT NULL,
  tdee numeric(6,1),
  calorias_objetivo numeric(6,1),
  proteina numeric(5,1),
  carbo numeric(5,1),
  grasa numeric(5,1),
  comidas jsonb,
  version integer DEFAULT 1,
  fecha timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- TABLA: FINANCES (Módulo Financiero y Facturación)
CREATE TABLE IF NOT EXISTS finances (
  id text PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  cliente text NOT NULL,
  concepto text NOT NULL,
  monto numeric(10,2) NOT NULL DEFAULT 0.00,
  tipo text DEFAULT 'ingreso',
  metodo_pago text DEFAULT 'efectivo',
  estado text DEFAULT 'completado',
  fecha timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- TABLA: LESIONES (Historial Clínico y Fisioterapéutico)
CREATE TABLE IF NOT EXISTS lesiones (
  id text PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  cliente text NOT NULL,
  zona text NOT NULL,
  diagnostico text,
  eva_dolor integer DEFAULT 0,
  fase text DEFAULT 'fase_1',
  ejercicios_contraindicados text[],
  notas text,
  fecha timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- TABLA: METRICAS_EVOLUCION (Check-ins y Fuerza 1RM)
CREATE TABLE IF NOT EXISTS metricas_evolucion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint REFERENCES clients(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  gym_id text NOT NULL DEFAULT 'gym_central_01',
  cliente text NOT NULL,
  mesociclo integer DEFAULT 1,
  peso numeric(5,2),
  grasa numeric(4,1),
  musculo numeric(4,1),
  rm_sentadilla numeric(5,2),
  rm_banca numeric(5,2),
  rm_muerto numeric(5,2),
  fecha timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- 2. ÍNDICES DE ALTO RENDIMIENTO PARA CONSULTAS Y CONCURRENCIA
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_clients_user_gym ON clients(user_id, gym_id);
CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email);
CREATE INDEX IF NOT EXISTS idx_clients_auth_user_id ON clients(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_clients_gym_id ON clients(gym_id);
CREATE INDEX IF NOT EXISTS idx_planes_user_gym ON planes(user_id, gym_id);
CREATE INDEX IF NOT EXISTS idx_planes_client_id ON planes(client_id);
CREATE INDEX IF NOT EXISTS idx_dietas_user_gym ON dietas(user_id, gym_id);
CREATE INDEX IF NOT EXISTS idx_dietas_client_id ON dietas(client_id);
CREATE INDEX IF NOT EXISTS idx_finances_user_gym ON finances(user_id, gym_id);
CREATE INDEX IF NOT EXISTS idx_finances_client_id ON finances(client_id);
CREATE INDEX IF NOT EXISTS idx_lesiones_client_id ON lesiones(client_id);
CREATE INDEX IF NOT EXISTS idx_metricas_client_id ON metricas_evolucion(client_id);

-- ------------------------------------------------------------------------------
-- 3. HABILITACIÓN DE REALTIME EN SUPABASE (PUBLICACIÓN REACTIVA)
-- ------------------------------------------------------------------------------
-- Asegurar que las réplicas contengan la información completa para DIFF en tiempo real
ALTER TABLE clients REPLICA IDENTITY FULL;
ALTER TABLE planes REPLICA IDENTITY FULL;
ALTER TABLE dietas REPLICA IDENTITY FULL;
ALTER TABLE finances REPLICA IDENTITY FULL;
ALTER TABLE metricas_evolucion REPLICA IDENTITY FULL;

-- Agregar tablas a la publicación de Supabase Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'clients'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE clients, planes, dietas, finances, metricas_evolucion;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL; -- Si la publicación no existe o ya está agregada, continuar
END $$;

-- ------------------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY (RLS) CON AISLAMIENTO POR GYM (TENANT), COACH Y ATLETA
-- ------------------------------------------------------------------------------
-- Las políticas de coach usan gym_id del JWT para aislar datos entre sedes.
-- Las políticas de atleta usan auth_user_id (UUID directo) para identidad segura,
-- con fallback a email para compatibilidad con registros legacy.
-- ------------------------------------------------------------------------------
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE planes ENABLE ROW LEVEL SECURITY;
ALTER TABLE dietas ENABLE ROW LEVEL SECURITY;
ALTER TABLE finances ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE metricas_evolucion ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas previas (incluye nombres legacy por si existen)
DROP POLICY IF EXISTS "coaches_all_clients" ON clients;
DROP POLICY IF EXISTS "coaches_gym_clients" ON clients;
DROP POLICY IF EXISTS "athletes_select_own_client" ON clients;
DROP POLICY IF EXISTS "athletes_update_own_client" ON clients;
DROP POLICY IF EXISTS "coaches_all_planes" ON planes;
DROP POLICY IF EXISTS "coaches_gym_planes" ON planes;
DROP POLICY IF EXISTS "athletes_select_own_planes" ON planes;
DROP POLICY IF EXISTS "coaches_all_dietas" ON dietas;
DROP POLICY IF EXISTS "coaches_gym_dietas" ON dietas;
DROP POLICY IF EXISTS "athletes_select_own_dietas" ON dietas;
DROP POLICY IF EXISTS "coaches_all_finances" ON finances;
DROP POLICY IF EXISTS "coaches_gym_finances" ON finances;
DROP POLICY IF EXISTS "athletes_select_own_finances" ON finances;
DROP POLICY IF EXISTS "coaches_all_lesiones" ON lesiones;
DROP POLICY IF EXISTS "coaches_gym_lesiones" ON lesiones;
DROP POLICY IF EXISTS "athletes_select_own_lesiones" ON lesiones;
DROP POLICY IF EXISTS "coaches_all_metricas" ON metricas_evolucion;
DROP POLICY IF EXISTS "coaches_gym_metricas" ON metricas_evolucion;
DROP POLICY IF EXISTS "athletes_select_own_metricas" ON metricas_evolucion;
DROP POLICY IF EXISTS "athletes_insert_own_metricas" ON metricas_evolucion;

-- POLÍTICAS CLIENTS
-- Coach/Admin: solo ve/edita clients de su propia sede (gym_id)
CREATE POLICY "coaches_gym_clients" ON clients
  FOR ALL
  USING (
    user_id = auth.uid()
    OR coach_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR coach_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve y edita su propio registro (por auth_user_id o email)
CREATE POLICY "athletes_select_own_client" ON clients
  FOR SELECT
  USING (
    auth_user_id = auth.uid()
    OR email = (auth.jwt() ->> 'email')
  );

CREATE POLICY "athletes_update_own_client" ON clients
  FOR UPDATE
  USING (
    auth_user_id = auth.uid()
    OR email = (auth.jwt() ->> 'email')
  )
  WITH CHECK (
    auth_user_id = auth.uid()
    OR email = (auth.jwt() ->> 'email')
  );

-- POLÍTICAS PLANES
-- Coach/Admin: planes de su propia sede
CREATE POLICY "coaches_gym_planes" ON planes
  FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve planes donde el client_id coincide con su registro
CREATE POLICY "athletes_select_own_planes" ON planes
  FOR SELECT
  USING (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );

-- POLÍTICAS DIETAS
-- Coach/Admin: dietas de su propia sede
CREATE POLICY "coaches_gym_dietas" ON dietas
  FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve dietas donde el client_id coincide con su registro
CREATE POLICY "athletes_select_own_dietas" ON dietas
  FOR SELECT
  USING (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );

-- POLÍTICAS FINANCES
-- Coach/Admin: finanzas de su propia sede
CREATE POLICY "coaches_gym_finances" ON finances
  FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve finanzas donde el client_id coincide con su registro
CREATE POLICY "athletes_select_own_finances" ON finances
  FOR SELECT
  USING (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );

-- POLÍTICAS LESIONES
-- Coach/Admin: lesiones de su propia sede
CREATE POLICY "coaches_gym_lesiones" ON lesiones
  FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve lesiones donde el client_id coincide con su registro
CREATE POLICY "athletes_select_own_lesiones" ON lesiones
  FOR SELECT
  USING (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );

-- POLÍTICAS MÉTRICAS DE EVOLUCIÓN
-- Coach/Admin: métricas de su propia sede
CREATE POLICY "coaches_gym_metricas" ON metricas_evolucion
  FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('coach', 'admin')
      AND gym_id = (auth.jwt() -> 'user_metadata' ->> 'gym_id')
    )
  );

-- Atleta: solo ve métricas donde el client_id coincide con su registro
CREATE POLICY "athletes_select_own_metricas" ON metricas_evolucion
  FOR SELECT
  USING (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );

-- Atleta: puede insertar sus propias métricas (check-ins)
CREATE POLICY "athletes_insert_own_metricas" ON metricas_evolucion
  FOR INSERT
  WITH CHECK (
    client_id IN (
      SELECT id FROM clients
      WHERE auth_user_id = auth.uid() OR email = (auth.jwt() ->> 'email')
    )
  );
