-- ==============================================================================
-- 🛡️ FITPRO SUITE PRO — REGISTRO DE EVENTOS DE ACCESO (OWASP A09)
-- ==============================================================================
-- Cómo aplicarlo: Supabase → SQL Editor → pegar este archivo → Run.
-- Es idempotente: se puede volver a ejecutar sin romper nada.
--
-- POR QUÉ EXISTE
-- Sin esto no queda rastro de los intentos de acceso fallidos: no hay forma de
-- notar un ataque de fuerza bruta contra la cuenta de un entrenador, ni de
-- responder "quién intentó entrar y cuándo" en una auditoría de compra.
--
-- Supabase guarda sus propios logs de Auth, pero en el plan gratuito se
-- retienen 1 día. Esta tabla vive en la base del proyecto, no caduca sola y
-- no cuesta nada.
--
-- QUIÉN ESCRIBE AQUÍ
-- Solo api/log-security-event.js, con la service_role (que ignora RLS). El
-- navegador nunca escribe directo: si pudiera, cualquiera podría inundar la
-- tabla con la clave anon, que es pública por diseño.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS security_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),

  -- 'login_fallido' | 'login_exitoso' | 'password_reset_solicitado' | 'password_cambiado'
  evento      text NOT NULL,

  -- El correo TECLEADO, que puede no corresponder a ninguna cuenta. Es
  -- justamente lo que interesa ver cuando alguien prueba direcciones al azar.
  email       text,

  -- Motivo devuelto por Supabase, recortado. Nunca contraseñas.
  motivo      text,

  ip          inet,
  user_agent  text,
  gym_id      text
);

-- Las tres preguntas que se le hacen a esta tabla: qué pasó últimamente,
-- quién intentó entrar a esta cuenta, y de dónde vienen los intentos.
CREATE INDEX IF NOT EXISTS security_events_created_at_idx ON security_events (created_at DESC);
CREATE INDEX IF NOT EXISTS security_events_email_idx      ON security_events (lower(email));
CREATE INDEX IF NOT EXISTS security_events_ip_idx         ON security_events (ip);

-- RLS activo y SIN políticas: eso deniega todo a las claves anon y
-- authenticated. La service_role no pasa por RLS, así que el endpoint sigue
-- escribiendo. Se consulta desde el SQL Editor del dashboard.
ALTER TABLE security_events ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- CONSULTAS ÚTILES
-- ------------------------------------------------------------------------------

-- Fallos de las últimas 24 horas, del más reciente al más viejo:
--   SELECT created_at, email, motivo, ip
--   FROM security_events
--   WHERE evento = 'login_fallido' AND created_at > now() - interval '24 hours'
--   ORDER BY created_at DESC;

-- Posible fuerza bruta: 5 o más fallos sobre la misma cuenta en una hora.
--   SELECT email, count(*) AS intentos, count(DISTINCT ip) AS ips, max(created_at) AS ultimo
--   FROM security_events
--   WHERE evento = 'login_fallido' AND created_at > now() - interval '1 hour'
--   GROUP BY email HAVING count(*) >= 5
--   ORDER BY intentos DESC;

-- ------------------------------------------------------------------------------
-- RETENCIÓN
-- ------------------------------------------------------------------------------
-- La tabla guarda correos e IPs, que son datos personales: conservarlos para
-- siempre no se justifica y en una auditoría juega en contra. 90 días alcanza
-- de sobra para investigar un incidente.
--
-- A mano, cuando toque:
--   DELETE FROM security_events WHERE created_at < now() - interval '90 days';
--
-- Automático, si el proyecto tiene pg_cron habilitado
-- (Database → Extensions → pg_cron):
--   SELECT cron.schedule(
--     'purgar-security-events',
--     '0 4 * * *',
--     $$DELETE FROM security_events WHERE created_at < now() - interval '90 days'$$
--   );
